### ISSUE TITLE
Relasi tabel Kategori dengan Transaksi ketika dihapus dan diupdate

### ISSUE THREAD

**Issue by ryfazrin** [ravihabibillah/money_writer_app#18]
- [ ] Apabila data kategori dihapus, namun masih digunakan oleh transaksi sebaiknya ada (2 opsi) :
 - [ ] peringatan bahwa data tidak bisa dihapus karena masih ada data transaksi yang terkait
 - [ ] peringatan bahwa ketika data dihapus, data transaksi yang terkait juga ikut terhapus hapus

**Comment by ryfazrin** [comment]
atau ada opsi lain?

**Comment by ravihabibillah** [comment]
bagusnya pilihan 2 aja
kalau misalkan pilihan 1, nanti usernya  masa harus ngapus item nya satu2 dulu baru ngapus kategorinya?

**Comment by ravihabibillah** [comment]
ini ada referensi buat ngubah actionnya
![image](https://user-images.githubusercontent.com/43630272/143833924-056423c5-d866-49e5-ad74-754584e099b5.png)

**Comment by ryfazrin** [comment]
ok berarti cascade ya.
ON DELETE CASCADE berarti bahwa jika catatan induk dihapus, semua catatan anak juga dihapus.

**Comment by ravihabibillah** [comment]
yoi
